copy cacic2.exe            O:\var\www\default\cacic2\repositorio /Y
copy chkcacic\chkcacic.exe O:\var\www\default\cacic2\repositorio /Y
copy chksis\chksis.exe O:\var\www\default\cacic2\repositorio /Y
copy ger_cols\ger_cols.exe O:\var\www\default\cacic2\repositorio /Y
copy ini_cols\ini_cols.exe O:\var\www\default\cacic2\repositorio /Y
copy col_anvi\col_anvi.exe O:\var\www\default\cacic2\repositorio /Y
copy col_comp\col_comp.exe O:\var\www\default\cacic2\repositorio /Y
copy col_hard\col_hard.exe O:\var\www\default\cacic2\repositorio /Y
copy col_moni\col_moni.exe O:\var\www\default\cacic2\repositorio /Y
copy col_patr\col_patr.exe O:\var\www\default\cacic2\repositorio /Y
copy col_soft\col_soft.exe O:\var\www\default\cacic2\repositorio /Y
copy col_undi\col_undi.exe O:\var\www\default\cacic2\repositorio /Y
